### ISSUE TITLE
Can not download the data

### ISSUE THREAD

**Issue by Hisham-Hussein** [elnagara/HARD-Arabic-Dataset#1]
Hello ... I am trying to download the data but the links provided don't work .. 

Thanks!

**Comment by Hisham-Hussein** [comment]
Update .. I downloaded it .. 

the issue persists with the BARD data set .. so I'll move the issue there

**Comment by elnagara** [comment]
Dear Hisham

Sorry to hear that you could not download the datasets. Please let me know
which one is still pending.

I appreciate replying to ***@***.***
For quick response.
Thanks & Regards
Ashraf

**Comment by Hisham-Hussein** [comment]
Hi .. thanks for your reply .. and thanks for creating the data set and
sharing it publicly.. it's very generous of you.

I downloaded the HARD dataset successfully.. the one i couldn't download is
the BRAD dataset. The external links provided don't work basically ..
nothing gets downloaded!

Also I suggest creating a very basic notebook on how to read the data into
a Pandas data frame. I spent a lot of time trying to read the data (the
HARD dataset) although I am fairly professional in Pandas ... It worked in
the end. Turns out I had to specify the encoding as "utf-16" .. which is
quite rare given that I had worked with numerous Arabic data sets before
and never had to use this encoding.

I can contribute this notebook containing some basic data analysis and
visualization to the repo if you'd allow me.

Thanks!

**Comment by elnagara** [comment]
Thank you for your kind offer to share your code. I can add it and of
course give you credit.

This was done 3 years ago. I didn't recall we had an issue reading the data
into pandas.

I will check BRAD links and get back to you.
Best wishes,

Ashraf

**Comment by Hisham-Hussein** [comment]
Okay .. thanks a lot!
